<?php
/**
 * @package   AkeebaLoginGuard
 * @copyright Copyright (c)2016-2017 Akeeba Ltd
 * @license   GNU General Public License version 3, or later
 */

// Prevent direct access
defined('_JEXEC') or die;

class LoginGuardControllerMethod extends JControllerLegacy
{
	/**
	 * The default model for this MVC triad. Something that Joomla fails to take into account...
	 *
	 * @var   JModelLegacy
	 */
	protected $default_model = null;

	/**
	 * Constructor.
	 *
	 * @param   array  $config  An optional associative array of configuration settings.
	 * Recognized key values include 'name', 'default_task', 'model_path', and
	 * 'view_path' (this list is not meant to be comprehensive).
	 */
	public function __construct(array $config = array())
	{
		// We have to tell Joomla what is the name of the view, otherwise it defaults to the name of the *component*.
		$config['default_view'] = 'Method';
		$config['default_task'] = 'add';

		parent::__construct($config);
	}
	/**
	 * Execute a task by triggering a method in the derived class.
	 *
	 * @param   string  $task  The task to perform. If no matching task is found, the '__default' task is executed, if defined.
	 *
	 * @return  mixed   The value returned by the called method.
	 *
	 * @since   3.0
	 * @throws  Exception
	 */
	public function execute($task)
	{
		// I wish I could use a single controller for plural and singular views - but I can't.
		if ($task == 'display')
		{
			$task = 'add';
		}

		return parent::execute($task); // TODO: Change the autogenerated stub
	}

	/**
	 * Add a new TFA method
	 *
	 * @param   bool   $cachable   Can this view be cached
	 * @param   array  $urlparams  An array of safe url parameters and their variable types, for valid values see {@link JFilterInput::clean()}.
	 *
	 * @return  JControllerLegacy   The current JControllerLegacy object to support chaining.
	 */
	public function add($cachable = false, $urlparams = array())
	{
		// Make sure the user is logged in
		$this->_assertLoggedIn();

		// Also make sure the method really does exist
		$method = $this->input->getCmd('method');
		$this->_assertMethodExists($method);

		/** @var LoginGuardModelMethod $model */
		$model = $this->getModel();
		$model->setState('method', $method);

		return parent::display($cachable, $urlparams);
	}


	/**
	 * Edit an existing TFA method
	 *
	 * @param   bool   $cachable   Can this view be cached
	 * @param   array  $urlparams  An array of safe url parameters and their variable types, for valid values see {@link JFilterInput::clean()}.
	 *
	 * @return  JControllerLegacy   The current JControllerLegacy object to support chaining.
	 */
	public function edit($cachable = false, $urlparams = array())
	{
		// Make sure the user is logged in
		$this->_assertLoggedIn();

		// Also make sure the method really does exist
		$id = $this->input->getInt('id');
		$record = $this->_assertValidRecordId($id);

		if ($id <= 0)
		{
			throw new RuntimeException(JText::_('JERROR_ALERTNOAUTHOR'), 403);
		}

		/** @var LoginGuardModelMethod $model */
		$model = $this->getModel();
		$model->setState('id', $id);

		return parent::display($cachable, $urlparams);
	}

	/**
	 * Save the TFA method
	 *
	 * @param   bool   $cachable   Can this view be cached
	 * @param   array  $urlparams  An array of safe url parameters and their variable types, for valid values see {@link JFilterInput::clean()}.
	 *
	 * @return  JControllerLegacy   The current JControllerLegacy object to support chaining.
	 */
	public function save($cachable = false, $urlparams = array())
	{
		// Make sure the user is logged in
		$this->_assertLoggedIn();

		// CSRF Check
		$token = JSession::getFormToken();
		$value = $this->input->post->getInt($token, 0);

		if ($value != 1)
		{
			die(JText::_('JINVALID_TOKEN'));
		}

		// The record must either be new (ID zero) or exist
		$id     = $this->input->getInt('id', 0);
		$record = $this->_assertValidRecordId($id);

		// If it's a new record we need to read the method from the request and update the (not yet created) record.
		if ($record->id == 0)
		{
			$methodName = $this->input->getCmd('method');
			$this->_assertMethodExists($methodName);
			$record->method = $methodName;
		}

		/** @var LoginGuardModelMethod $model */
		$model = $this->getModel();

		// Ask the plugin to validate the input by calling onLoginGuardTfaSaveSetup
		$result = array();
		$input  = JFactory::getApplication()->input;

		try
		{
			$pluginResults = LoginGuardHelperTfa::runPlugins('onLoginGuardTfaSaveSetup', array($record, $input));

			foreach ($pluginResults as $pluginResult)
			{
				$result = array_merge($result, $pluginResult);
			}
		}
		catch (RuntimeException $e)
		{
			// Go back to the edit page
			$nonSefUrl = 'index.php?option=com_loginguard&task=method.';

			if ($id)
			{
				$nonSefUrl .= 'edit&id=' . (int) $id;
			}
			else
			{
				$nonSefUrl .= 'add';
			}

			$url = JRoute::_($nonSefUrl);
			$this->setRedirect($url, $e->getMessage(), 'error');
		}

		// Update the record's options with the plugin response
		$title = $this->input->getString('title', null);
		$title = trim($title);

		if (empty($title))
		{
			$method = $model->getMethod($record->method);
			$title  = $method['display'];
		}

		// Update the record's "default" flag
		$default         = $this->input->getBool('default', false);
		$record->title   = $title;
		$record->options = json_encode($result);
		$record->default = $default ? 1 : 0;

		// Ask the model to save the record
		try
		{
			$model->saveRecord($record);
		}
		catch (Exception $e)
		{
			// Go back to the edit page
			$nonSefUrl = 'index.php?option=com_loginguard&task=method.';

			if ($id)
			{
				$nonSefUrl .= 'edit&id=' . (int) $id;
			}
			else
			{
				$nonSefUrl .= 'add';
			}

			$url = JRoute::_($nonSefUrl);
			$this->setRedirect($url, $e->getMessage(), 'error');
		}

		$this->setRedirect(JRoute::_('index.php?option=com_loginguard&task=methods.display'));

		return $this;
	}

	/**
	 * Method to get a model object, loading it ONLY if required.
	 *
	 * Unlike core Joomla, only one instance of the default model will be created. This lets us pass Model state from
	 * the Controller, i.e. implement ARCHITECTURALLY CORRECT MVC for a change.
	 *
	 * @param   string  $name    The model name. Optional.
	 * @param   string  $prefix  The class prefix. Optional.
	 * @param   array   $config  Configuration array for model. Optional.
	 *
	 * @return  JModelLegacy|boolean  Model object on success; otherwise false on failure.
	 */
	public function getModel($name = '', $prefix = '', $config = array())
	{
		$isDefaultModel = (empty($name) || ($name == 'Method')) && empty($prefix);

		if ($isDefaultModel)
		{
			if (is_null($this->default_model))
			{
				$this->default_model = parent::getModel('Method', $prefix, $config);
			}

			return $this->default_model;
		}

		return parent::getModel($name, $prefix, $config);
	}

	/**
	 * Assert that the provided ID is a valid record identified for the given user
	 *
	 * @param   int    $id    Record ID to check
	 * @param   JUser  $user  User record. Null to use current user.
	 *
	 * @return  stdClass  The loaded record
	 *
	 * @throws  RuntimeException  When the record ID is invalid or does not belong to the specified user.
	 */
	private function _assertValidRecordId($id, JUser $user = null)
	{
		if (is_null($user))
		{
			$user = JFactory::getUser();
		}

		/** @var LoginGuardModelMethod $model */
		$model = $this->getModel();

		$model->setState('id', $id);

		$record = $model->getRecord($user);

		if (is_null($record) || ($record->id != $id) || ($record->user_id != $user->id))
		{
			throw new RuntimeException(JText::_('JERROR_ALERTNOAUTHOR'), 403);
		}

		return $record;
	}

	/**
	 * Assert that the user is logged in.
	 *
	 * @param   JUser  $user  User record. Null to use current user.
	 *
	 * @throws  RuntimeException  When the user is a guest (not logged in)
	 */
	private function _assertLoggedIn(JUser $user = null)
	{
		if (is_null($user))
		{
			$user = JFactory::getUser();
		}

		if ($user->guest)
		{
			throw new RuntimeException(JText::_('JERROR_ALERTNOAUTHOR'), 403);
		}
	}

	/**
	 * Assert that the specified TFA method exists, is activated and enabled for the current user
	 *
	 * @param   string  $method  The method to check
	 *
	 * @return  void
	 *
	 * @throws  RuntimeException  If the TFA method does nto exist
	 */
	private function _assertMethodExists($method)
	{
		/** @var LoginGuardModelMethod $model */
		$model = $this->getModel();

		if (!$model->methodExists($method))
		{
			throw new RuntimeException(JText::_('JERROR_ALERTNOAUTHOR'), 403);
		}
	}

}