SET QUOTED_IDENTIFIER ON;

CREATE TABLE [#__loginguard_tfa] (
  [id] [bigint] IDENTITY(1,1) NOT NULL,
  [user_id] [BIGINT] NOT NULL DEFAULT 0 ,
  [title] [NVARCHAR](180) NOT NULL,
  [method] [NVARCHAR](100) NOT NULL,
  [default] [SMALLINT] NOT NULL DEFAULT 0 ,
  [options] [nvarchar](max) NOT NULL,
  [created_on] [datetime] NOT NULL DEFAULT '1900-01-01T00:00:00.000',
  [last_used] [datetime] NOT NULL DEFAULT '1900-01-01T00:00:00.000',
  [ua] [VARCHAR](190) NULL,
  [ip] [VARCHAR](190) NULL,
  CONSTRAINT [PK_#__loginguard_tfa_id] PRIMARY KEY CLUSTERED (
    [id] ASC
  )WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY];

CREATE NONCLUSTERED INDEX [__loginguard_tfa_user_id] ON [#__loginguard_tfa]
(
  [user_id] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF);
